image: node:14

variables:
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: -ffdx -e .cache_yarn -e build -e node_modules -e yarn.lock -e .env


stages:
  - install
  - build
  - test
  - deploy

install_node_modules:
  stage: install
  script:
    - yarn install --cache-folder .cache_yarn
  only:
    - develop
    - production
  tags:
    - local



build_frontend:
  stage: build
  script:
    - cp .env.development .env
    - yarn build
  only:
    - develop
    - master
  dependencies:
    - install_node_modules
  artifacts:
    paths:
      - build
  tags:
    - local


test_client:
  stage: test
  script:
    - echo "Run test"
  only:
    - develop
    - master
  dependencies:
    - install_node_modules

deploy_all_develop:
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no -r build savvycom@10.22.4.142:~/savvy-dex-fe-react/build
  only:
    - develop
  environment:
    name: staging
  dependencies:
    - install_node_modules
    - build_frontend
  tags:
    - local

deploy_all_production:
  stage: deploy
  script:
    - echo "TODO deploy to production"
  only:
    - master
  environment:
    name: production
  dependencies:
    - install_node_modules
    - build_frontend
  tags:
    - local
