image: node:14

variables:
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: -ffdx -e .cache_yarn -e .next -e node_modules -e yarn.lock -e .env


stages:
  - install
  - build
  - test
  - deploy

install_node_modules:
  stage: install
  script:
    - yarn install --cache-folder .cache_yarn
  only:
    - develop
    - production
  tags:
    - local



build_frontend:
  stage: build
  script:
    - cp .env.development .env
    - yarn build
  only:
    - develop
    - master
  dependencies:
    - install_node_modules
  tags:
    - local


test_client:
  stage: test
  script:
    - echo "Run test..."
  only:
    - develop
    - master
  dependencies:
    - install_node_modules
  tags:
    - local

deploy_all_develop:
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no -r .next savvycom@10.22.4.142:~/dex-savvy-fe/
    - scp -o StrictHostKeyChecking=no -r .env savvycom@10.22.4.142:~/dex-savvy-fe/
    - scp -o StrictHostKeyChecking=no -r public savvycom@10.22.4.142:~/dex-savvy-fe/
    - ssh -tt -o StrictHostKeyChecking=no savvycom@10.22.4.142 "cd dex-savvy-fe && git pull && yarn install && pm2 reload dex && exit"
  only:
    - develop
  environment:
    name: staging
  dependencies:
    - install_node_modules
    - build_frontend
  tags:
    - local

build_frontend_production:
  stage: build
  script:
    - cp .env.production .env
    - yarn build
  only:
    - savvydex-v1
  dependencies:
    - install_node_modules
  tags:
    - local

deploy_all_production:
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no -r .next savvycom@172.105.122.187:/opt/dex/dex-savvy-fe/
    - scp -o StrictHostKeyChecking=no -r .env savvycom@172.105.122.187:/opt/dex/dex-savvy-fe/
    - scp -o StrictHostKeyChecking=no -r public savvycom@172.105.122.187:/opt/dex/dex-savvy-fe/
    - ssh -tt -o StrictHostKeyChecking=no savvycom@172.105.122.187 "cd dex-savvy-fe && git pull && yarn install && pm2 reload dex && exit"
  only:
    - savvydex-v1
  environment:
    name: production
  dependencies:
    - install_node_modules
    - build_frontend_production
  tags:
    - local
