image: node:14

variables:
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: -ffdx -e .cache_yarn -e build -e node_modules


stages:
  - install
  - build
  - test
  - deploy

install_node_modules:
  stage: install
  script:
    - yarn install --cache-folder .cache_yarn
  only:
    - develop
    - production
  tags:
    - local



build_frontend:
  stage: build
  script:
    - yarn build
  only:
    - develop
    - master
  dependencies:
    - install_node_modules
  artifacts:
    paths:
      - build
  tags:
    - local


test_client:
  stage: test
  script:
    - echo "Run test"
  only:
    - develop
    - master
  dependencies:
    - install_node_modules

deploy_all_develop:
  stage: deploy
  script:
    - yarn global add firebase-tools --cache-folder ../.cache_yarn
    - firebase --token $FIREBASE_DEPLOY_KEY_STAGING --project staging deploy
  only:
    - develop
  environment:
    name: staging
  dependencies:
    - install_node_modules
    - build_frontend
  tags:
    - local

deploy_all_production:
  stage: deploy
  script:
    - echo "deploy to production"
  only:
    - master
  environment:
    name: production
  dependencies:
    - install_node_modules
    - build_frontend
  tags:
    - local
