image: node:14

cache:
  key: cache_yarn
  paths:
    - .cache_yarn

stages:
  - install
  - build
  - test
  - deploy

install_node_modules:
  stage: install
  script:
    - yarn install --cache-folder .cache_yarn
  only:
    - develop
    - production
  artifacts:
    paths:
      - node_modules



build_frontend:
  stage: build
  script:
    - yarn build
  only:
    - develop
    - master
  dependencies:
    - install_node_modules
  artifacts:
    paths:
      - build


test_client:
  stage: test
  script:
    - echo "Run test"
  only:
    - develop
    - master
  dependencies:
    - install_node_modules

deploy_all_develop:
  stage: deploy
  script:
    - yarn global add firebase-tools --cache-folder ../.cache_yarn
    - firebase --token $FIREBASE_DEPLOY_KEY_STAGING --project staging deploy
  only:
    - develop
  environment:
    name: staging
  dependencies:
    - install_node_modules
    - build_frontend

deploy_all_production:
  stage: deploy
  script:
    - echo "deploy to production"
  only:
    - master
  environment:
    name: production
  dependencies:
    - install_functions
    - build_client
